<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_womens top179</name>
   <tag></tag>
   <elementGuidId>8279d52e-488d-4824-8830-db3a2c091afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='qs-option-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qs-option-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1ec0753e-09ed-4433-932d-6fbbfea13630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>11db5589-6b7b-472a-b763-0d0800b4826b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qs-option-2</value>
      <webElementGuid>cfe4c89f-93cb-460a-9e79-dbc089e4e627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0d3b3aed-e064-4d8e-979e-8f84cac47a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> women's top179</value>
      <webElementGuid>28e4955a-3efb-451b-b2fd-6ed2f548063c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qs-option-2&quot;)</value>
      <webElementGuid>99a8f8f6-7ee1-441f-a1ee-f6378206a059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='qs-option-2']</value>
      <webElementGuid>c8be3c50-7fb4-4836-b871-8f4ecfc14a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_autocomplete']/ul/li[3]</value>
      <webElementGuid>c74f33ee-6b12-4313-bc58-0969b5b943e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='women'])[1]/following::li[2]</value>
      <webElementGuid>37d52f6f-55d7-451e-aa50-6bbd51d658d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('women', &quot;'&quot;, 's tops')])[1]/preceding::li[1]</value>
      <webElementGuid>18c03e06-6f33-4ff6-9347-aef6cd357302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]</value>
      <webElementGuid>005a3f9b-ed92-4bf6-9e1c-5f2343b23c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'qs-option-2' and (text() = concat(&quot; women&quot; , &quot;'&quot; , &quot;s top179&quot;) or . = concat(&quot; women&quot; , &quot;'&quot; , &quot;s top179&quot;))]</value>
      <webElementGuid>add658fa-eea1-4976-a0ec-6506c8b26c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
