<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sale</name>
   <tag></tag>
   <elementGuidId>5d52c831-1860-499c-aa6a-ef3afee9c475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store.menu']/nav/ul/li[6]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.level0.nav-6.category-item.last.level-top > a.level-top > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbba42fa-bb3b-4065-90a3-0d0f145da659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sale</value>
      <webElementGuid>07d520bf-d07c-4c43-8b83-f5b6b9e2ab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store.menu&quot;)/nav[@class=&quot;navigation&quot;]/ul[1]/li[@class=&quot;level0 nav-6 category-item last level-top&quot;]/a[@class=&quot;level-top&quot;]/span[1]</value>
      <webElementGuid>dbb18d8d-786d-4d8a-a6bd-6d0d99960ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store.menu']/nav/ul/li[6]/a/span</value>
      <webElementGuid>11c44e05-13be-458b-9b64-50c5bf46463c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Download'])[1]/following::span[1]</value>
      <webElementGuid>d7b242f5-99a2-460f-85a3-8a1b94e7f3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training'])[1]/following::span[2]</value>
      <webElementGuid>98294185-f183-40f5-989c-d835ffd0b68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/preceding::span[1]</value>
      <webElementGuid>4ce11ede-5945-4f58-844c-0bc48ee6e265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[2]/preceding::span[3]</value>
      <webElementGuid>f65591fa-1795-4156-bb13-566b2d016433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sale']/parent::*</value>
      <webElementGuid>2e1b933f-a5cf-4894-97b2-8b81a1e79fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>9f4b5ade-47ad-46d9-a79f-78c3e31eb7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sale' or . = 'Sale')]</value>
      <webElementGuid>3b0e0b07-05fd-41a9-b55c-1c323d7487ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
