<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to Wish List</name>
   <tag></tag>
   <elementGuidId>3f99df9a-2b3b-43b9-9705-041a14d7e1e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action.towishlist</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div/div[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2604c06f-2613-49f7-9466-c4983af733f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cb8e38c0-a16c-42fa-9442-0b4ba39d78ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action towishlist</value>
      <webElementGuid>e61f20ea-f3d7-456e-a521-81fbd5660aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-post</name>
      <type>Main</type>
      <value>{&quot;action&quot;:&quot;https:\/\/magento.softwaretestingboard.com\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:712,&quot;uenc&quot;:&quot;aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS90aWJlcml1cy1neW0tdGFuay5odG1s&quot;}}</value>
      <webElementGuid>12541b8c-02a6-45be-958b-65c1f193482f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>add-to-wishlist</value>
      <webElementGuid>22f4b0d6-64ec-467c-954f-e31b1411999f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Wish List</value>
      <webElementGuid>9922e996-f41e-4dd5-a6f4-d301c5758c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;product-info-main&quot;]/div[@class=&quot;product-social-links&quot;]/div[@class=&quot;product-addto-links&quot;]/a[@class=&quot;action towishlist&quot;]</value>
      <webElementGuid>5fd6837e-275c-49b5-b3c8-b022bf2a3b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/div[5]/div/a</value>
      <webElementGuid>d23b962b-6af6-45b1-9abd-08d17fe5f9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/following::a[1]</value>
      <webElementGuid>0bb5defa-2b54-4b2f-b1e4-9042f2dc6244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::a[1]</value>
      <webElementGuid>732a80b4-2220-4bcb-9ed3-ae1f9246119e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Compare'])[1]/preceding::a[1]</value>
      <webElementGuid>0716bac2-59d1-43d2-8889-7ff6744ef4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>e07f786c-3e2e-4e93-a9cc-bad8976a118c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>88520ca9-dd50-49af-a067-9ac48f05ef16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Add to Wish List' or . = 'Add to Wish List')]</value>
      <webElementGuid>ce9893bb-c913-4712-bc0f-c7d03073c625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
