<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bottoms</name>
   <tag></tag>
   <elementGuidId>2a48c740-f49e-429e-bbad-304b56d76174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dl[@id='narrow-by-list2']/dd/ol/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72f989a0-c9fb-48bd-a964-83162c14f4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/women/bottoms-women.html</value>
      <webElementGuid>308678a1-add0-4a72-94c6-b7b67aaad9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bottoms</value>
      <webElementGuid>78954e31-cb02-4d16-bc6e-896a2b93cbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;narrow-by-list2&quot;)/dd[1]/ol[@class=&quot;items&quot;]/li[@class=&quot;item&quot;]/a[1]</value>
      <webElementGuid>0cb99389-428e-4e75-8946-4c77f5fd494d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='narrow-by-list2']/dd/ol/li[2]/a</value>
      <webElementGuid>49ce1de2-9c27-429c-ae18-ce7316486d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bottoms')]</value>
      <webElementGuid>bfd72b22-b510-4838-9a36-36318e2ee503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[3]/following::a[1]</value>
      <webElementGuid>fa7b1d73-b873-44d9-b47e-f6278d01b3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::a[2]</value>
      <webElementGuid>355c2b0d-060f-44fc-b8b2-a28c62ca0fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[4]/preceding::a[1]</value>
      <webElementGuid>5b8da957-d871-4f72-88bc-be9b51f4b1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoodies &amp; Sweatshirts'])[3]/preceding::a[1]</value>
      <webElementGuid>a12531ec-bf79-4b9d-ade0-f8be5979cf91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://magento.softwaretestingboard.com/women/bottoms-women.html')])[2]</value>
      <webElementGuid>c66a91cd-f94a-4351-8fd1-6aeff7cbd2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]/a</value>
      <webElementGuid>ae9be738-c20b-4420-899a-296ec64f081c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/women/bottoms-women.html' and (text() = 'Bottoms' or . = 'Bottoms')]</value>
      <webElementGuid>d9c76df1-1126-49f2-a92b-5a501967c7c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
